# Generated by Django 4.0.6 on 2022-09-28 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0037_gameprofile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='reply_to_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page3.post'),
        ),
    ]
