# Generated by Django 4.0.6 on 2022-10-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0038_replies_reply_to_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_primary_reply',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
