# Generated by Django 4.0.6 on 2022-10-01 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0039_post_is_primary_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_primary_reply',
            new_name='is_parent_a_reply',
        ),
    ]
