# Generated by Django 4.0.6 on 2022-10-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0040_rename_is_primary_reply_post_is_parent_a_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_root',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
