# Generated by Django 4.0.6 on 2022-10-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0041_post_reply_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='reply_root',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
