# Generated by Django 4.0.6 on 2022-10-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0042_replies_reply_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
