# Generated by Django 3.2.15 on 2022-10-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0044_post_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, null=True)),
                ('post', models.ManyToManyField(blank=True, default=None, related_name='tagged_posts', to='page3.Post')),
            ],
        ),
    ]
